"""add block5

Revision ID: e7d8ad7af0b6
Revises: 20260319_01
Create Date: 2026-03-23 07:47:31.621442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8ad7af0b6'
down_revision: Union[str, None] = '20260319_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_constraint('paper_content_paper_id_key', 'paper_content', type_='unique')
    op.drop_constraint('paper_source_meta_paper_id_key', 'paper_source_meta', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('paper_source_meta_paper_id_key', 'paper_source_meta', ['paper_id'])
    op.create_unique_constraint('paper_content_paper_id_key', 'paper_content', ['paper_id'])
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
